In [4]:
%pylab

import numpy as np
import nibabel as nib
from dipy.reconst.peaks import peaks_from_model, PeaksAndMetrics
from dipy.core.sphere import Sphere
from dipy.data import get_sphere
from dipy.io.gradients import read_bvals_bvecs
from dipy.core.gradients import gradient_table
from dipy.tracking import utils
from common import load_nifti, save_trk, save_peaks, load_peaks, save_trk_old_style
from dipy.viz import actor, window, fvtk

Using matplotlib backend: MacOSX
Populating the interactive namespace from numpy and matplotlib


In [27]:
dname = '/Users/ghfc/Desktop/Ferret_ExplDTI/P32_F16/'

fbval = dname + 'P32_F16.bval' 
fbvec = dname + 'P32_F16.bvec'

bvals, bvecs = read_bvals_bvecs(fbval, fbvec)

gtab = gradient_table(bvals, bvecs, b0_threshold=50)

In [28]:
gtab.gradients

array([[    0.        ,     0.        ,     0.        ],
       [    0.        ,     0.        ,     0.        ],
       [    0.        ,     0.        ,     0.        ],
       [    0.        ,     0.        ,     0.        ],
       [    0.        ,     0.        ,     0.        ],
       [    0.        ,     0.        ,     0.        ],
       [    0.        ,     0.        ,     0.        ],
       [    0.        ,     0.        ,     0.        ],
       [    0.        ,     0.        ,     0.        ],
       [    0.        ,     0.        ,     0.        ],
       [ -546.73942499,   866.2420351 , -1756.17983251],
       [  800.96159065,  -955.52743231, -1637.44601854],
       [  921.88014007,  -409.36859646,  1809.87315325],
       [ -267.30442308, -1891.35303599,   622.93136997],
       [-1608.7951984 ,   607.99927397, -1025.0761324 ],
       [ 1177.6525216 , -1689.0092209 ,  -150.18785482],
       [ 1131.92871064,  -788.59274452, -1543.97657229],
       [-1377.18857335,  -258.2

In [30]:
# permute columns 
#x[:,[2,1]] = x[:,[1,2]]
gtab.gradients[:,[1,0]] = gtab.gradients[:,[0,1]]

In [31]:
gtab.gradients

array([[    0.        ,     0.        ,     0.        ],
       [    0.        ,     0.        ,     0.        ],
       [    0.        ,     0.        ,     0.        ],
       [    0.        ,     0.        ,     0.        ],
       [    0.        ,     0.        ,     0.        ],
       [    0.        ,     0.        ,     0.        ],
       [    0.        ,     0.        ,     0.        ],
       [    0.        ,     0.        ,     0.        ],
       [    0.        ,     0.        ,     0.        ],
       [    0.        ,     0.        ,     0.        ],
       [  866.2420351 ,  -546.73942499, -1756.17983251],
       [ -955.52743231,   800.96159065, -1637.44601854],
       [ -409.36859646,   921.88014007,  1809.87315325],
       [-1891.35303599,  -267.30442308,   622.93136997],
       [  607.99927397, -1608.7951984 , -1025.0761324 ],
       [-1689.0092209 ,  1177.6525216 ,  -150.18785482],
       [ -788.59274452,  1131.92871064, -1543.97657229],
       [ -258.2571879 , -1377.1

In [32]:
# multiply column 2 of the 2D array, A, by 5.2
# A[:,1] *= 5.2
gtab.gradients[:,1] *= -1

In [33]:
gtab.gradients

array([[    0.        ,    -0.        ,     0.        ],
       [    0.        ,    -0.        ,     0.        ],
       [    0.        ,    -0.        ,     0.        ],
       [    0.        ,    -0.        ,     0.        ],
       [    0.        ,    -0.        ,     0.        ],
       [    0.        ,    -0.        ,     0.        ],
       [    0.        ,    -0.        ,     0.        ],
       [    0.        ,    -0.        ,     0.        ],
       [    0.        ,    -0.        ,     0.        ],
       [    0.        ,    -0.        ,     0.        ],
       [  866.2420351 ,   546.73942499, -1756.17983251],
       [ -955.52743231,  -800.96159065, -1637.44601854],
       [ -409.36859646,  -921.88014007,  1809.87315325],
       [-1891.35303599,   267.30442308,   622.93136997],
       [  607.99927397,  1608.7951984 , -1025.0761324 ],
       [-1689.0092209 , -1177.6525216 ,  -150.18785482],
       [ -788.59274452, -1131.92871064, -1543.97657229],
       [ -258.2571879 ,  1377.1